Convert check title into a default job The job can run in parallel as we do not have to use the version number at this time. If the job fails, it should stop all other jobs and states from being executed that are not already running. We do not check here if the version number is available because there may be several merge requests with the same version as title that are not necessarily merged. I'm not sure if variables will be overwritten by each team's variables.

diff --git a/base_pipeline.yml b/base_pipeline.yml
--- a/base_pipeline.yml
+++ b/base_pipeline.yml
@@ -8,6 +8,12 @@ stages:
 # Standard job image
 image: gitlab.sdu.dk:5050/semester-project-e2021/team-12/ci-cd/base_image:0.0.1
 
+variables:
+  # Regex to check version number
+  #  Regex has been changed from having not captured groups
+  #  See https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
+  CI_CD_SEMVER_REGEX: '^(0|[1-9]\d*)\\.(0|[1-9]\d*)\\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$'
+
 ### Rules ###
 # Trigger rules
 .default:
@@ -137,15 +143,6 @@ image: gitlab.sdu.dk:5050/semester-project-e2021/team-12/ci-cd/base_image:0.0.1
     - curl -u "${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}" "https://gitlab.com/jwt/auth?account=${CI_REGISTRY_USER}&scope=repository:${CI_REGISTRY_IMAGE}/${CI_CD_IMAGE_NAME}:delete&service=container_registry"
     - reg -d -r ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} rm "${CI_PROJECT_PATH}/${CI_CD_IMAGE_NAME}:${CI_CD_TAG}"
 
-.check_for_tag:
-  image: gitlab.sdu.dk:5050/semester-project-e2021/team-12/ci-cd/docker:0.0.1
-  script:
-    - apk add jq
-    - 'if [[ ! ${CI_MERGE_REQUEST_TITLE} =~ [0-9]+\.[0-9]+\.[0-9]+ ]] && [ "${CI_MERGE_REQUEST_TITLE}" != "mockup" ]; then echo "ERROR: Wrong version number format. - See https://gitlab.sdu.dk/semester-project-e2021/team-12/ci-cd/-/wikis/Guide" ; exit 1; fi'
-    - 'IMAGE_ID=$(curl --header "PRIVATE-TOKEN: ${PROJECT_TOKEN}" "https://gitlab.sdu.dk/api/v4/projects/${CI_PROJECT_ID}/registry/repositories/" | jq ".[] | select(.name == \"${CI_CD_IMAGE_NAME}\") | .id")'
-    - if [ -z "${IMAGE_ID}" ]; then exit 0; fi
-    - 'if [ $(curl --header "PRIVATE-TOKEN: ${PROJECT_TOKEN}" "https://gitlab.sdu.dk/api/v4/projects/${CI_PROJECT_ID}/registry/repositories/${IMAGE_ID}/tags" | jq ". | map(.name==\"${CI_MERGE_REQUEST_TITLE}\") | any") == "true" ]; then echo "ERROR: Version number already exist. - See https://gitlab.sdu.dk/semester-project-e2021/team-12/ci-cd/-/wikis/Guide" ; exit 1; fi'
-
 .artifact:
   artifacts:
     expose_as: "Artifact"
@@ -155,6 +152,17 @@ image: gitlab.sdu.dk:5050/semester-project-e2021/team-12/ci-cd/base_image:0.0.1
     expire_in: 3 hrs
 
 ### Jobs ###
+build:check_request_title:
+  extends:
+    - .build
+    - .merge_request_production_branch
+  script:
+    - |
+      if [[ ! ${CI_MERGE_REQUEST_TITLE} =~ ${CI_CD_SEMVER_REGEX} ]]; then
+        echo "ERROR: Wrong request title. - See https://gitlab.sdu.dk/semester-project-e2021/team-12/ci-cd/-/wikis/Guide";
+        exit 1;
+      fi
+
 finish:failure:
   stage: finish
   extends: .on_failure
