Fix semver tool

diff --git a/docker_images/base_image/Dockerfile b/docker_images/base_image/Dockerfile
--- a/docker_images/base_image/Dockerfile
+++ b/docker_images/base_image/Dockerfile
@@ -1,8 +1,8 @@
 FROM alpine:3.13
 
 # Install curl, jq and semver tool
-# https://github.com/fsaintjacques/semver-tool
-RUN apk --no-cache add curl jq wget && \
-    wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver && \
-    chmod +x /usr/local/bin/semver && \
-    apk --no-cache del wget
+# Semver tool: https://github.com/fsaintjacques/semver-tool (depend on bash)
+RUN apk --no-cache add curl jq bash && \
+    curl -fSL "https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver" -o "/usr/local/bin/semver" && \
+    if [ "$(echo "d5055fc17cf00a1d56107746a991ba0b6ef817fcfc063459c1eacedbb277bbd5  /usr/local/bin/semver" | sha256sum -c -)" == "/usr/local/bin/reg: OK" ]; then echo "ERROR: semver has wrong check sum"; exit 1; fi && \
+    chmod a+x "/usr/local/bin/semver"
diff --git a/docker_images/docker/Dockerfile b/docker_images/docker/Dockerfile
--- a/docker_images/docker/Dockerfile
+++ b/docker_images/docker/Dockerfile
@@ -2,11 +2,11 @@ FROM docker:20.10
 
 # Install curl, jq, Docker registry v2 and semver tool
 # Docker registry v2: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/40096
-# Semver tool: https://github.com/fsaintjacques/semver-tool
-RUN apk --no-cache add curl jq git wget && \
+# Semver tool: https://github.com/fsaintjacques/semver-tool (depend on bash)
+RUN apk --no-cache add curl jq git bash && \
     curl -fSL "https://github.com/genuinetools/reg/releases/download/v0.13.0/reg-linux-amd64" -o "/usr/local/bin/reg" && \
     if [ "$(echo "d6096b30d8b0eefe3ba57895769ca5bfdade5c7105dc5995e3029e8d70877e06 /usr/local/bin/reg" | sha256sum -c -)" == "/usr/local/bin/reg: OK" ]; then echo "ERROR: reg has wrong check sum"; exit 1; fi && \
     chmod a+x "/usr/local/bin/reg" &&  \
-    wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver && \
-    chmod +x /usr/local/bin/semver && \
-    apk --no-cache del wget
+    curl -fSL "https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver" -o "/usr/local/bin/semver" && \
+    if [ "$(echo "d5055fc17cf00a1d56107746a991ba0b6ef817fcfc063459c1eacedbb277bbd5  /usr/local/bin/semver" | sha256sum -c -)" == "/usr/local/bin/reg: OK" ]; then echo "ERROR: semver has wrong check sum"; exit 1; fi && \
+    chmod a+x "/usr/local/bin/semver"
